### ISSUE TITLE
display bug: display of mm count switch to 2 lines and back to 1 line several times by second. (blinking)

### ISSUE THREAD

**Issue by yannickbattail** [Eregrith/MousePro#10]
display in 2 lines
maybe related to [https://github.com/Eregrith/MousePro/issues/9](url)
![2018-10-01 1](https://user-images.githubusercontent.com/1282175/46287233-20b5b600-c582-11e8-888b-cfd2c3b7caca.png)

**Comment by Eregrith** [comment]
It appears to be fixed by 28c2f56 as well
